name: Copy files to GCP-VM

on:
  workflow_run:
    workflows: ["Install Apache-Server"]
    types:
      - completed 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to GCP VM
        uses: appleboy/scp-action@master 
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USERNAME }}
          key: ${{ secrets.GCP_VM_PRIVATE_KEY }}
          source: "."  
          target: "/var/www/html"  # Target directory on GCP VM

      - name: restart apache2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USERNAME }}
          key: ${{ secrets.GCP_VM_PRIVATE_KEY }}
          script: |
            sudo systemctl restart apache2 
